kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  podSubnet: "172.16.0.0/16"
  serviceSubnet: "172.17.0.0/16"
  apiServerAddress: "192.168.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
