kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
networking:
  ipFamily: "ipv4"
  disableDefaultCNI: true
  kubeProxyMode: "none"
  podSubnet: "10.20.0.0/16"
  serviceSubnet: "10.21.0.0/16"
  apiServerAddress: ${CURRENT_IP}
  apiServerPort: 6443
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta4
  kind: ClusterConfiguration
  apiServer:
    timeoutForControlPlane: 10m
    extraArgs:
      allow-privileged: "true"
      audit-log-path: /audit/k8s-api-audit.log
      audit-log-maxage: "7"
      audit-log-maxbackup: "4"
      audit-log-maxsize: "100"
      authorization-mode: Node,RBAC
    extraVolumes:
      - name: audit-kubernetes
        hostPath: /var/log/kubernetes
        mountPath: /audit
        readOnly: false
        pathType: DirectoryOrCreate
  controllerManager:
    extraArgs:
      allocate-node-cidrs: "true"
      cluster-cidr: 10.20.0.0/16
      # feature-gates: VolumeSnapshotDataSource=true
      node-cidr-mask-size: "24"
  controlPlaneEndpoint: ${CURRENT_IP}:6443
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  cgroupDriver: systemd
  clusterDNS:
    - 10.21.0.10
  clusterDomain: cluster.local
  serializeImagePulls: false
  resolvConf: "/files/resolv.conf.k8s"

nodes:
- role: control-plane
  #image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  extraMounts:
  - hostPath: /files
    containerPath: /files
    propagation: HostToContainer
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: InitConfiguration
    nodeRegistration:
      name: control-plane
      taints: []
      kubeletExtraArgs:
        node-labels: "operator-home=true,bgp=cluster"
- role: worker
  #image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  extraMounts:
  - hostPath: /files
    containerPath: /files
    propagation: HostToContainer
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: JoinConfiguration
    nodeRegistration:
      name: worker-1
      taints: []
      kubeletExtraArgs:
        node-labels: "minio=local,operator-home=true,bgp=cluster"
- role: worker
  #image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  extraMounts:
  - hostPath: /files
    containerPath: /files
    propagation: HostToContainer
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: JoinConfiguration
    nodeRegistration:
      name: worker-2
      taints: []
      kubeletExtraArgs:
        node-labels: "minio=local,bgp=cluster"
- role: worker
  #image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  extraMounts:
  - hostPath: /files
    containerPath: /files
    propagation: HostToContainer
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: JoinConfiguration
    nodeRegistration:
      name: worker-3
      taints: []
      kubeletExtraArgs:
        node-labels: "minio=local,bgp=cluster"
